### ISSUE TITLE
docker-custodian crashing when cleaning up.

### ISSUE THREAD

**Issue by hasannizamani** [Yelp/docker-custodian#38] opened 2016-10-09 23:02 UTC
Getting the error when running docker-custodian:

```
Traceback (most recent call last):
  File "/usr/bin/dcgc", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: backports.ssl-match-hostname>=3.5
```

**Comment by solarkennedy** [comment] 2016-10-10 14:40
Dupe of #37

**Closed by solarkennedy** 2016-10-10 14:40 UTC
